services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: ./server
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_BACKEND=redis://redis:6379/0
      - REDIS_BROKER=redis://redis:6379/0
  
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - API_SERVER=app:8000
    
  celery_worker:
    container_name: celery_worker
    build: ./tasks
    depends_on:
      - redis
    environment:
      - REDIS_BACKEND=redis://redis:6379/0
      - REDIS_BROKER=redis://redis:6379/0
  
  ai_worker:
    container_name: ai_worker
    build: ./ai
    depends_on:
      - redis
    environment:
      - REDIS_BACKEND=redis://redis:6379/0
      - REDIS_BROKER=redis://redis:6379/0
    secrets:
      - mistral_ai_key

secrets:
  mistral_ai_key:
    file: ./.secrets/mistralai_key
